In [1]:
import pandas as pd
import numpy as np
import os

print("Project started successfully!")

Project started successfully!

In [2]:
print(os.getcwd())

C:\Users\ajith\Desktop\Employee_Attrition_MLOps

In [4]:
df = pd.read_csv("mlops_employee_attrition_dataset.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (500, 10)

In [5]:
df.head()

,employee_id,age,experience_years,salary,department,education,job_satisfaction,work_life_balance,training_hours,attrition
0,1,59,13,137599,Sales,Bachelors,1,2,27,1
1,2,49,30,55678,Operations,Bachelors,5,4,41,0
2,3,35,4,101218,Operations,Masters,1,5,42,0
3,4,28,34,88230,IT,Bachelors,1,3,41,0
4,5,41,22,139684,Sales,Bachelors,2,4,65,0

In [6]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Missing values:
employee_id          0
age                  0
experience_years     0
salary               0
department           0
education            0
job_satisfaction     0
work_life_balance    0
training_hours       0
attrition            0
dtype: int64

Duplicate rows:
0

Data types:
employee_id           int64
age                   int64
experience_years      int64
salary                int64
department           object
education            object
job_satisfaction      int64
work_life_balance     int64
training_hours        int64
attrition             int64
dtype: object

In [7]:
print(df["attrition"].value_counts())

attrition
0    342
1    158
Name: count, dtype: int64

In [8]:
for col in df.columns:
    print("\n", col)
    print(df[col].unique())

 employee_id
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500]

 age
[59 49 35 28 41 39 43 31 44 56 23 42 22 50 58 53 32 45 47 48 36 57 27 29
 38 24 34 46 40 55 37 26 54 30 51 21 25 33 52]

 experience_years
[13 30  4 34 22 28 10 17 11  8  9 16  6 12 26  1 18  7  0 21 24  3  5 25
  2 27 19 32 31 20 15 14 23 29 33]

 salary
[137599  55678 101218  88230 139684  99055  81373  56480 110230  93836
  97258  64986  49160 110595 126358 104111  89929  98506  59911 112127
  56821 100039  85535 138453 109458  37175 144235  79771 131660 146300
 111925 138374  91358  42327  72057  31150  29425 148654  41032  27198
  85500  78394  45079  61220  66874  38859  75460  56419 143865  33705
  67880  48236 112955 110514 128145  40358 124713 119914 127870 101918
 144179 141243  39596  58572 103757  26279  88197 136496  87516  32083
 145674 145307 134397  42771  54975  70648  73285  44063  92642 115093
 139390 111143  62599  76920  53529  60954  52856  27573 103344  60367
 127337 131732 124608  85774  48752  80029  42685  76693 141739  80961
 131937 149956 101908  99532 106994  81133 122425  86268 117201  63243
  82384  56653  51657  64952  47180 122432 146829 103411  26622  73756
  65809  41725  86396  76226 131296 106182 107565  54402  29263 148489
 121523  71828 145824  72924  99182 118065  84052  36664  60737 126332
 114563  54373 142369  61397 111145 126371  63709 141074  86120  44250
  46172  36555 112410 103617  78276  82492  78002 145103 149938 114599
  97355 116248  49762  36046 121999 149130 141021  53769  78302  48150
  93247  29853 119613 145900 114399  46792  84129 131019  99478 138811
 139130  92298  56987  40850  37112 146789  49058  70420  63890  91017
  72304  57921 130921  26524 125424  40048  60111  62904  79912  59008
  25060  99666 108559  80337 135616  38350  49354  70186  53145  59020
 111123 131667 100186 110469  45581 113929  48051  76474 116748 139618
  94626  31960  60772  46520  74481  61408 119006  82134  45491  26341
  69623 115327  25338  96431  37254  76860  36344  26750  79756  92957
 130423  83053  95855  40896  80761  87552 145075 102454 143681 115600
 147732 137153 147926  52935  62641  54711  95342 131896  37182 112833
  81276  44541 119457 107310  69813  62198  33820  49070  94768  36122
 105559  98543 108441  66786 119934 124804  31737  61062  79237  76571
  50510  44426  62265  42850 143249  91150 112312 114613  99910  77375
 146826  60435 121443  82132 103945 107050 120402  27983 122241  45662
  48510 103187  65998  81846 119071  31640  69547  79620  40317 140608
  32564  52345 138824 119223 148372 104273  99859 105765 135017  99038
 148618  77393  91081 127650  54430 100532  52788 120505  73543  38919
  94346 121122  64974 132309  41371  70084  54629  76184  86916  98972
  87187  37984  58039 110431 108691  83606  35616 127665 130373  75072
  49574  28430 144123  37676  35816  57733 110680  27050 134996  58933
  49951  57413  59801  80619  57913 137573 144076  65600  82775 115816
 137590  60400  29494 105688 147744 114431  99691 122419 133730  68001
  92364 149988  70028 132434 122659  62573  25806 149343  81638 131506
  54757  59636 105097  73280  49262 105435  87211  79842  81979 139524
 106470  63197  66844  89754 126868  59157 102129  65042  86665 140512
 141953 107856  52376 134049  80554  39199 143533 106412  75948  98781
  97750  91262 142424  71600 101898  87483  43297  55448  51172  67874
  32657 109386  50425  51685 147000 137855  49578  53831  32906  86413
  79028  32287  58660 100758  85504  84720 127979  59701 108300 135177
  42674 108560 136543  48874  68642 148867 122820  90160  42602 128320
 113801  50931 119377  54192  71542  67520  89772  83762  75106 106121
  50559 130595  58742  94669 105199  46754  28972  95831 137217  66873
 119661 131532  34903  28020  66755 110956 111988 128537  34516 137863
 140005  27396 109082  44129  26591  36303  55561  96719]

 department
['Sales' 'Operations' 'IT' 'Finance' 'HR']

 education
['Bachelors' 'Masters' 'PhD']

 job_satisfaction
[1 5 2 4 3]

 work_life_balance
[2 4 5 3 1]

 training_hours
[27 41 42 65 54 71 47 21 26 66 12 44  9  8 53 33  0 31 70 19 34 77 16 17
 52 67 64 57 25 58 74 40  4 68 10 55 50 20 75 18 59 46 39  3 22 14  7 45
 36 23 62 60 35 56 48 61 69  6 37  2 49 29 24 38 15 30 73 51 72  5 63 32
 13 28 79 43  1 11 78 76]

 attrition
[1 0]

In [9]:
import os

os.makedirs("data/raw", exist_ok=True)

df.to_csv(
    "data/raw/employee_attrition_raw.csv",
    index=False
)

print("Raw dataset saved successfully!")

Raw dataset saved successfully!

In [10]:
print(os.path.exists("data/raw/employee_attrition_raw.csv"))

True

In [11]:
raw_df = pd.read_csv("data/raw/employee_attrition_raw.csv")

print("Raw data shape:", raw_df.shape)
raw_df.head()

Raw data shape: (500, 10)

,employee_id,age,experience_years,salary,department,education,job_satisfaction,work_life_balance,training_hours,attrition
0,1,59,13,137599,Sales,Bachelors,1,2,27,1
1,2,49,30,55678,Operations,Bachelors,5,4,41,0
2,3,35,4,101218,Operations,Masters,1,5,42,0
3,4,28,34,88230,IT,Bachelors,1,3,41,0
4,5,41,22,139684,Sales,Bachelors,2,4,65,0

In [12]:
processed_df = df.copy()

processed_df = processed_df.drop_duplicates()

print("Original rows:", len(df))
print("Rows after removing duplicates:", len(processed_df))

Original rows: 500
Rows after removing duplicates: 500

In [13]:
print("Missing values before:")
print(processed_df.isnull().sum())

Missing values before:
employee_id          0
age                  0
experience_years     0
salary               0
department           0
education            0
job_satisfaction     0
work_life_balance    0
training_hours       0
attrition            0
dtype: int64

In [14]:
for col in processed_df.columns:
    if processed_df[col].dtype == "object":
        processed_df[col] = processed_df[col].fillna(processed_df[col].mode()[0])
    else:
        processed_df[col] = processed_df[col].fillna(processed_df[col].median())

print("Missing values after:")
print(processed_df.isnull().sum())

Missing values after:
employee_id          0
age                  0
experience_years     0
salary               0
department           0
education            0
job_satisfaction     0
work_life_balance    0
training_hours       0
attrition            0
dtype: int64

In [15]:
os.makedirs("data/processed", exist_ok=True)

processed_df.to_csv(
    "data/processed/employee_attrition_processed.csv",
    index=False
)

print("Processed dataset saved successfully!")
print("Shape:", processed_df.shape)

Processed dataset saved successfully!
Shape: (500, 10)

In [16]:
print(os.path.exists("data/processed/employee_attrition_processed.csv"))

True

In [17]:
feature_df = pd.read_csv(
    "data/processed/employee_attrition_processed.csv"
)

print("Processed data loaded!")
print(feature_df.shape)

Processed data loaded!
(500, 10)

In [18]:
feature_df["salary_per_experience"] = (
    feature_df["salary"] / (feature_df["experience_years"] + 1)
)

feature_df["training_per_experience"] = (
    feature_df["training_hours"] / (feature_df["experience_years"] + 1)
)

feature_df["satisfaction_score"] = (
    feature_df["job_satisfaction"] +
    feature_df["work_life_balance"]
)

print("New features created!")
print(feature_df.head())

New features created!
   employee_id  age  experience_years  salary  department  education  \
0            1   59                13  137599       Sales  Bachelors
1            2   49                30   55678  Operations  Bachelors
2            3   35                 4  101218  Operations    Masters
3            4   28                34   88230          IT  Bachelors
4            5   41                22  139684       Sales  Bachelors

   job_satisfaction  work_life_balance  training_hours  attrition  \
0                 1                  2              27          1
1                 5                  4              41          0
2                 1                  5              42          0
3                 1                  3              41          0
4                 2                  4              65          0

   salary_per_experience  training_per_experience  satisfaction_score
0            9828.500000                 1.928571                   3
1            1796.064516                 1.322581                   9
2           20243.600000                 8.400000                   6
3            2520.857143                 1.171429                   4
4            6073.217391                 2.826087                   6

In [21]:
print(feature_df.columns.tolist())

['employee_id', 'age', 'experience_years', 'salary', 'job_satisfaction', 'work_life_balance', 'training_hours', 'attrition', 'salary_per_experience', 'training_per_experience', 'satisfaction_score', 'department_Finance', 'department_HR', 'department_IT', 'department_Operations', 'department_Sales', 'education_Bachelors', 'education_Masters', 'education_PhD']

In [22]:
print(feature_df["attrition"].unique())

[nan]

In [23]:
# Reload the processed dataset
feature_df = pd.read_csv(
    "data/processed/employee_attrition_processed.csv"
)

# Create the engineered features again
feature_df["salary_per_experience"] = (
    feature_df["salary"] / (feature_df["experience_years"] + 1)
)

feature_df["training_per_experience"] = (
    feature_df["training_hours"] / (feature_df["experience_years"] + 1)
)

feature_df["satisfaction_score"] = (
    feature_df["job_satisfaction"] +
    feature_df["work_life_balance"]
)

print(feature_df["attrition"].unique())

[1 0]

In [24]:
os.makedirs("data/features", exist_ok=True)

feature_df.to_csv(
    "data/features/employee_attrition_features.csv",
    index=False
)

print("Feature-engineered dataset saved successfully!")
print("Shape:", feature_df.shape)

Feature-engineered dataset saved successfully!
Shape: (500, 13)

In [25]:
print(os.path.exists("data/features/employee_attrition_features.csv"))

True

In [26]:
X = feature_df.drop(columns=["attrition", "employee_id"])
y = feature_df["attrition"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (500, 11)
y shape: (500,)

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 400
Testing samples: 100

In [29]:
# Load the feature-engineered dataset
feature_df = pd.read_csv(
    "data/features/employee_attrition_features.csv"
)

# Check the columns
print(feature_df.columns.tolist())

['employee_id', 'age', 'experience_years', 'salary', 'department', 'education', 'job_satisfaction', 'work_life_balance', 'training_hours', 'attrition', 'salary_per_experience', 'training_per_experience', 'satisfaction_score']

In [30]:
X = feature_df.drop(columns=["attrition", "employee_id"])
y = feature_df["attrition"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (500, 11)
y shape: (500,)

In [31]:
print("Non-numeric columns:")
print(X.select_dtypes(include=["object"]).columns.tolist())

Non-numeric columns:
['department', 'education']

In [32]:
# Encode categorical columns
X = pd.get_dummies(
    feature_df.drop(columns=["attrition", "employee_id"]),
    columns=["department", "education"],
    dtype=int
)

y = feature_df["attrition"]

print("Non-numeric columns:")
print(X.select_dtypes(include=["object"]).columns.tolist())

print("\nX shape:", X.shape)
print("y shape:", y.shape)

Non-numeric columns:
[]

X shape: (500, 17)
y shape: (500,)

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 400
Testing samples: 100

In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling completed!")
print("Training data:", X_train_scaled.shape)
print("Testing data:", X_test_scaled.shape)

Scaling completed!
Training data: (400, 17)
Testing data: (100, 17)

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [36]:
model1 = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model1.fit(X_train_scaled, y_train)

print("Logistic Regression trained successfully!")

Logistic Regression trained successfully!

In [37]:
y_pred1 = model1.predict(X_test_scaled)

print("Predictions completed!")

Predictions completed!

In [38]:
accuracy1 = accuracy_score(y_test, y_pred1)
precision1 = precision_score(y_test, y_pred1, zero_division=0)
recall1 = recall_score(y_test, y_pred1, zero_division=0)
f1_1 = f1_score(y_test, y_pred1, zero_division=0)

print("Logistic Regression Results")
print("---------------------------")
print("Accuracy :", accuracy1)
print("Precision:", precision1)
print("Recall   :", recall1)
print("F1 Score :", f1_1)

Logistic Regression Results
---------------------------
Accuracy : 0.79
Precision: 0.7037037037037037
Recall   : 0.59375
F1 Score : 0.6440677966101694

In [39]:
from sklearn.tree import DecisionTreeClassifier

In [40]:
model2 = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

model2.fit(X_train, y_train)

print("Decision Tree trained successfully!")

Decision Tree trained successfully!

In [41]:
y_pred2 = model2.predict(X_test)

print("Predictions completed!")

Predictions completed!

In [42]:
accuracy2 = accuracy_score(y_test, y_pred2)
precision2 = precision_score(y_test, y_pred2, zero_division=0)
recall2 = recall_score(y_test, y_pred2, zero_division=0)
f1_2 = f1_score(y_test, y_pred2, zero_division=0)

print("Decision Tree Results")
print("---------------------")
print("Accuracy :", accuracy2)
print("Precision:", precision2)
print("Recall   :", recall2)
print("F1 Score :", f1_2)

Decision Tree Results
---------------------
Accuracy : 0.83
Precision: 0.7419354838709677
Recall   : 0.71875
F1 Score : 0.7301587301587301

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
model3 = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)

model3.fit(X_train, y_train)

print("Random Forest trained successfully!")

Random Forest trained successfully!

In [45]:
y_pred3 = model3.predict(X_test)

print("Predictions completed!")

Predictions completed!

In [46]:
accuracy3 = accuracy_score(y_test, y_pred3)
precision3 = precision_score(y_test, y_pred3, zero_division=0)
recall3 = recall_score(y_test, y_pred3, zero_division=0)
f1_3 = f1_score(y_test, y_pred3, zero_division=0)

print("Random Forest Results")
print("---------------------")
print("Accuracy :", accuracy3)
print("Precision:", precision3)
print("Recall   :", recall3)
print("F1 Score :", f1_3)

Random Forest Results
---------------------
Accuracy : 0.89
Precision: 1.0
Recall   : 0.65625
F1 Score : 0.7924528301886793

In [47]:
from sklearn.svm import SVC

In [48]:
model4 = SVC(
    C=1.0,
    kernel="rbf",
    random_state=42
)

model4.fit(X_train_scaled, y_train)

print("SVM trained successfully!")

SVM trained successfully!

In [49]:
y_pred4 = model4.predict(X_test_scaled)

print("Predictions completed!")

Predictions completed!

In [50]:
accuracy4 = accuracy_score(y_test, y_pred4)
precision4 = precision_score(y_test, y_pred4, zero_division=0)
recall4 = recall_score(y_test, y_pred4, zero_division=0)
f1_4 = f1_score(y_test, y_pred4, zero_division=0)

print("SVM Results")
print("-----------")
print("Accuracy :", accuracy4)
print("Precision:", precision4)
print("Recall   :", recall4)
print("F1 Score :", f1_4)

SVM Results
-----------
Accuracy : 0.81
Precision: 0.8095238095238095
Recall   : 0.53125
F1 Score : 0.6415094339622641

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
model5 = KNeighborsClassifier(
    n_neighbors=5
)

model5.fit(X_train_scaled, y_train)

print("KNN trained successfully!")

KNN trained successfully!

In [53]:
y_pred5 = model5.predict(X_test_scaled)

print("Predictions completed!")

Predictions completed!

In [54]:
accuracy5 = accuracy_score(y_test, y_pred5)
precision5 = precision_score(y_test, y_pred5, zero_division=0)
recall5 = recall_score(y_test, y_pred5, zero_division=0)
f1_5 = f1_score(y_test, y_pred5, zero_division=0)

print("KNN Results")
print("-----------")
print("Accuracy :", accuracy5)
print("Precision:", precision5)
print("Recall   :", recall5)
print("F1 Score :", f1_5)

KNN Results
-----------
Accuracy : 0.77
Precision: 0.7368421052631579
Recall   : 0.4375
F1 Score : 0.5490196078431373

In [55]:
from sklearn.ensemble import GradientBoostingClassifier

In [56]:
model6 = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

model6.fit(X_train, y_train)

print("Gradient Boosting trained successfully!")

Gradient Boosting trained successfully!

In [57]:
y_pred6 = model6.predict(X_test)

print("Predictions completed!")

Predictions completed!

In [58]:
accuracy6 = accuracy_score(y_test, y_pred6)
precision6 = precision_score(y_test, y_pred6, zero_division=0)
recall6 = recall_score(y_test, y_pred6, zero_division=0)
f1_6 = f1_score(y_test, y_pred6, zero_division=0)

print("Gradient Boosting Results")
print("-------------------------")
print("Accuracy :", accuracy6)
print("Precision:", precision6)
print("Recall   :", recall6)
print("F1 Score :", f1_6)

Gradient Boosting Results
-------------------------
Accuracy : 0.87
Precision: 0.8518518518518519
Recall   : 0.71875
F1 Score : 0.7796610169491526

In [59]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "SVM",
        "KNN",
        "Gradient Boosting"
    ],
    "Accuracy": [
        accuracy1,
        accuracy2,
        accuracy3,
        accuracy4,
        accuracy5,
        accuracy6
    ],
    "Precision": [
        precision1,
        precision2,
        precision3,
        precision4,
        precision5,
        precision6
    ],
    "Recall": [
        recall1,
        recall2,
        recall3,
        recall4,
        recall5,
        recall6
    ],
    "F1 Score": [
        f1_1,
        f1_2,
        f1_3,
        f1_4,
        f1_5,
        f1_6
    ]
})

results

                 Model  Accuracy  Precision   Recall  F1 Score
0  Logistic Regression      0.79   0.703704  0.59375  0.644068
1        Decision Tree      0.83   0.741935  0.71875  0.730159
2        Random Forest      0.89   1.000000  0.65625  0.792453
3                  SVM      0.81   0.809524  0.53125  0.641509
4                  KNN      0.77   0.736842  0.43750  0.549020
5    Gradient Boosting      0.87   0.851852  0.71875  0.779661

In [60]:
best_model_row = results.loc[results["F1 Score"].idxmax()]

print("Best model based on F1 Score:")
print(best_model_row)

Best model based on F1 Score:
Model        Random Forest
Accuracy              0.89
Precision              1.0
Recall             0.65625
F1 Score          0.792453
Name: 2, dtype: object

In [61]:
results.to_csv(
    "model_comparison.csv",
    index=False
)

print("Model comparison saved successfully!")

Model comparison saved successfully!

In [62]:
pip install mlflow

Requirement already satisfied: mlflow in C:\Users\ajith\anaconda3\Lib\site-packages (3.15.1)
Requirement already satisfied: mlflow-skinny==3.15.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (3.15.1)
Requirement already satisfied: mlflow-tracing==3.15.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (3.15.1)
Requirement already satisfied: Flask-CORS<7 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (6.0.5)
Requirement already satisfied: Flask<4 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (3.14.1)
Requirement already satisfied: alembic!=1.10.0,<2 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (1.19.1)
Requirement already satisfied: cryptography<50,>=43.0.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (49.0.0)
Requirement already satisfied: docker<8,>=4.0.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (7.2.0)
Requirement already satisfied: graphene<4 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: huey<4,>=2.5.4 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (3.3.4)
Requirement already satisfied: matplotlib<4 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (3.11.0)
Requirement already satisfied: numpy<3 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (2.4.6)
Requirement already satisfied: pandas<3 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<26,>=4.0.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (23.0.1)
Requirement already satisfied: scikit-learn<2 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (1.9.0)
Requirement already satisfied: scipy<2 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (1.18.0)
Requirement already satisfied: skops<1 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (2.0.51)
Requirement already satisfied: waitress<4 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<8,>=5.0.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (6.2.2)
Requirement already satisfied: click<9,>=7.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (8.4.1)
Requirement already satisfied: cloudpickle<4 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (0.133.0)
Requirement already satisfied: fastapi<1 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (0.141.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (3.1.50)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (1.44.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (1.44.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (1.44.0)
Requirement already satisfied: packaging<27 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (26.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (6.33.5)
Requirement already satisfied: pydantic<3,>=2.0.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (1.2.1)
Requirement already satisfied: pyyaml<7,>=5.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (2.34.2)
Requirement already satisfied: sqlparse<1,>=0.4.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (0.6.0)
Requirement already satisfied: starlette<2 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (4.16.0)
Requirement already satisfied: uvicorn<1 in C:\Users\ajith\anaconda3\Lib\site-packages (from mlflow-skinny==3.15.1->mlflow) (0.40.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\ajith\anaconda3\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from aiohttp<4,>=3.7.0->mlflow) (1.24.2)
Requirement already satisfied: Mako in C:\Users\ajith\anaconda3\Lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.4.1)
Requirement already satisfied: colorama in C:\Users\ajith\anaconda3\Lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.15.1->mlflow) (0.4.6)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from cryptography<50,>=43.0.0->mlflow) (2.1.0)
Requirement already satisfied: google-auth~=2.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (2.56.3)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\ajith\anaconda3\Lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (2.7.0)
Requirement already satisfied: pywin32>=304 in C:\Users\ajith\anaconda3\Lib\site-packages (from docker<8,>=4.0.0->mlflow) (312)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\ajith\anaconda3\Lib\site-packages (from fastapi<1->mlflow-skinny==3.15.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\ajith\anaconda3\Lib\site-packages (from fastapi<1->mlflow-skinny==3.15.1->mlflow) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in C:\Users\ajith\anaconda3\Lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow) (4.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (0.4.2)
Requirement already satisfied: graphql-core<3.3,>=3.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from graphene<4->mlflow) (3.2.11)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in C:\Users\ajith\anaconda3\Lib\site-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.15.1->mlflow) (3.23.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\ajith\anaconda3\Lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pillow>=9 in C:\Users\ajith\anaconda3\Lib\site-packages (from matplotlib<4->mlflow) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\ajith\anaconda3\Lib\site-packages (from matplotlib<4->mlflow) (3.2.5)
Requirement already satisfied: opentelemetry-semantic-conventions==0.65b0 in C:\Users\ajith\anaconda3\Lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.15.1->mlflow) (0.65b0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ajith\anaconda3\Lib\site-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\Users\ajith\anaconda3\Lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow) (2.46.4)
Requirement already satisfied: six>=1.5 in C:\Users\ajith\anaconda3\Lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ajith\anaconda3\Lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\ajith\anaconda3\Lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\ajith\anaconda3\Lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (2026.6.17)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from scikit-learn<2->mlflow) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\ajith\anaconda3\Lib\site-packages (from scikit-learn<2->mlflow) (3.5.0)
Requirement already satisfied: prettytable>=3.9 in C:\Users\ajith\anaconda3\Lib\site-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: greenlet>=1 in C:\Users\ajith\anaconda3\Lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.3.2)
Requirement already satisfied: anyio<5,>=3.6.2 in C:\Users\ajith\anaconda3\Lib\site-packages (from starlette<2->mlflow-skinny==3.15.1->mlflow) (4.12.1)
Requirement already satisfied: h11>=0.8 in C:\Users\ajith\anaconda3\Lib\site-packages (from uvicorn<1->mlflow-skinny==3.15.1->mlflow) (0.16.0)
Requirement already satisfied: pycparser in C:\Users\ajith\anaconda3\Lib\site-packages (from cffi>=2.0.0->cryptography<50,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: wcwidth>=0.3.5 in C:\Users\ajith\anaconda3\Lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in C:\Users\ajith\anaconda3\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (0.6.4)
Note: you may need to restart the kernel to use updated packages.

In [63]:
import os

os.makedirs("mlruns", exist_ok=True)

print("MLflow folder ready!")

MLflow folder ready!

In [64]:
import mlflow

mlflow.set_tracking_uri("sqlite:///mlflow.db")

print("MLflow Tracking URI:")
print(mlflow.get_tracking_uri())

MLflow Tracking URI:
sqlite:///mlflow.db

In [65]:
mlflow.set_experiment("Employee_Attrition_Experiment")

print("MLflow experiment ready!")

2026/09/18 08:20:10 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/09/18 08:20:10 INFO mlflow.store.db.utils: Updating database tables
2026/09/18 08:20:13 INFO mlflow.tracking.fluent: Experiment with name 'Employee_Attrition_Experiment' does not exist. Creating a new experiment.

MLflow experiment ready!

In [66]:
experiment = mlflow.get_experiment_by_name(
    "Employee_Attrition_Experiment"
)

print("Experiment name:", experiment.name)
print("Experiment ID:", experiment.experiment_id)

Experiment name: Employee_Attrition_Experiment
Experiment ID: 1

In [67]:
with mlflow.start_run(run_name="Logistic_Regression"):

    # Log model parameters
    mlflow.log_param("model", "Logistic Regression")
    mlflow.log_param("max_iter", 1000)

    # Log evaluation metrics
    mlflow.log_metric("accuracy", accuracy1)
    mlflow.log_metric("precision", precision1)
    mlflow.log_metric("recall", recall1)
    mlflow.log_metric("f1_score", f1_1)

    # Log the trained model
    mlflow.sklearn.log_model(
        model1,
        "model"
    )

    print("Logistic Regression logged to MLflow!")

2026/09/18 08:20:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Logistic Regression logged to MLflow!

In [70]:
print(runs.columns.tolist())

['run_id', 'experiment_id', 'status', 'artifact_uri', 'start_time', 'end_time', 'metrics.recall', 'metrics.f1_score', 'metrics.accuracy', 'metrics.precision', 'params.model', 'params.max_iter', 'tags.mlflow.source.name', 'tags.mlflow.runName', 'tags.mlflow.user', 'tags.mlflow.source.type']

In [71]:
print(runs[
    [
        "run_id",
        "params.model",
        "metrics.accuracy",
        "metrics.precision",
        "metrics.recall",
        "metrics.f1_score"
    ]
])

                             run_id         params.model  metrics.accuracy  \
0  dea54456c59f4c7eb1202915ed4cbe68  Logistic Regression              0.79

   metrics.precision  metrics.recall  metrics.f1_score
0           0.703704         0.59375          0.644068

In [72]:
with mlflow.start_run(run_name="Decision_Tree"):
    mlflow.log_param("model", "Decision Tree")
    mlflow.log_param("max_depth", 5)

    mlflow.log_metric("accuracy", accuracy2)
    mlflow.log_metric("precision", precision2)
    mlflow.log_metric("recall", recall2)
    mlflow.log_metric("f1_score", f1_2)

    mlflow.sklearn.log_model(model2, "model")

    print("Decision Tree logged to MLflow!")

2026/09/18 08:22:49 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Decision Tree logged to MLflow!

In [73]:
with mlflow.start_run(run_name="Random_Forest"):
    mlflow.log_param("model", "Random Forest")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("max_depth", 5)

    mlflow.log_metric("accuracy", accuracy3)
    mlflow.log_metric("precision", precision3)
    mlflow.log_metric("recall", recall3)
    mlflow.log_metric("f1_score", f1_3)

    mlflow.sklearn.log_model(model3, "model")

    print("Random Forest logged to MLflow!")

2026/09/18 08:23:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Random Forest logged to MLflow!

In [74]:
with mlflow.start_run(run_name="SVM"):
    mlflow.log_param("model", "SVM")
    mlflow.log_param("C", 1.0)
    mlflow.log_param("kernel", "rbf")

    mlflow.log_metric("accuracy", accuracy4)
    mlflow.log_metric("precision", precision4)
    mlflow.log_metric("recall", recall4)
    mlflow.log_metric("f1_score", f1_4)

    mlflow.sklearn.log_model(model4, "model")

    print("SVM logged to MLflow!")

2026/09/18 08:24:02 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

SVM logged to MLflow!

In [75]:
with mlflow.start_run(run_name="KNN"):
    mlflow.log_param("model", "KNN")
    mlflow.log_param("n_neighbors", 5)

    mlflow.log_metric("accuracy", accuracy5)
    mlflow.log_metric("precision", precision5)
    mlflow.log_metric("recall", recall5)
    mlflow.log_metric("f1_score", f1_5)

    mlflow.sklearn.log_model(model5, "model")

    print("KNN logged to MLflow!")

2026/09/18 08:24:22 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

KNN logged to MLflow!

In [76]:
with mlflow.start_run(run_name="Gradient_Boosting"):
    mlflow.log_param("model", "Gradient Boosting")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("learning_rate", 0.1)
    mlflow.log_param("max_depth", 3)

    mlflow.log_metric("accuracy", accuracy6)
    mlflow.log_metric("precision", precision6)
    mlflow.log_metric("recall", recall6)
    mlflow.log_metric("f1_score", f1_6)

    mlflow.sklearn.log_model(model6, "model")

    print("Gradient Boosting logged to MLflow!")

2026/09/18 08:24:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Gradient Boosting logged to MLflow!

In [77]:
runs = mlflow.search_runs()

print("Total MLflow runs:", len(runs))

print(
    runs[
        [
            "run_id",
            "params.model",
            "metrics.accuracy",
            "metrics.precision",
            "metrics.recall",
            "metrics.f1_score"
        ]
    ]
)

Total MLflow runs: 6
                             run_id         params.model  metrics.accuracy  \
0  047b690c613e41319d560a967e46327c    Gradient Boosting              0.87
1  09fbcfe072764a32963b09ac1ff3715d                  KNN              0.77
2  bdfb746c1b7e4a8da578c451b4de073f                  SVM              0.81
3  77b8bad91586477689c5e7b25219d3a4        Random Forest              0.89
4  7043eab0623f402196900aadf2af9c07        Decision Tree              0.83
5  dea54456c59f4c7eb1202915ed4cbe68  Logistic Regression              0.79

   metrics.precision  metrics.recall  metrics.f1_score
0           0.851852         0.71875          0.779661
1           0.736842         0.43750          0.549020
2           0.809524         0.53125          0.641509
3           1.000000         0.65625          0.792453
4           0.741935         0.71875          0.730159
5           0.703704         0.59375          0.644068

In [78]:
best_run = runs.loc[runs["metrics.f1_score"].idxmax()]

print("Best Model:")
print("Model:", best_run["params.model"])
print("Run ID:", best_run["run_id"])
print("Accuracy:", best_run["metrics.accuracy"])
print("Precision:", best_run["metrics.precision"])
print("Recall:", best_run["metrics.recall"])
print("F1 Score:", best_run["metrics.f1_score"])

Best Model:
Model: Random Forest
Run ID: 77b8bad91586477689c5e7b25219d3a4
Accuracy: 0.89
Precision: 1.0
Recall: 0.65625
F1 Score: 0.7924528301886793

In [79]:
best_run_id = best_run["run_id"]

model_uri = f"runs:/{best_run_id}/model"

registered_model = mlflow.register_model(
    model_uri=model_uri,
    name="Employee_Attrition_Model"
)

print("Model registered successfully!")
print("Model name:", registered_model.name)
print("Version:", registered_model.version)

Successfully registered model 'Employee_Attrition_Model'.
2026/09/18 08:27:34 WARNING mlflow.tracking._model_registry.fluent: Run with id 77b8bad91586477689c5e7b25219d3a4 has no artifacts at artifact path 'model', registering model based on models:/m-f0a66fae1ee041ee80df95a37e5c014b instead

Model registered successfully!
Model name: Employee_Attrition_Model
Version: 1

Created version '1' of model 'Employee_Attrition_Model'.

In [80]:
from sklearn.ensemble import RandomForestClassifier

# Changed hyperparameters
model_v2 = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    random_state=42
)

# Train Version 2
model_v2.fit(X_train, y_train)

# Predict
y_pred_v2 = model_v2.predict(X_test)

# Metrics
accuracy_v2 = accuracy_score(y_test, y_pred_v2)
precision_v2 = precision_score(y_test, y_pred_v2, zero_division=0)
recall_v2 = recall_score(y_test, y_pred_v2, zero_division=0)
f1_v2 = f1_score(y_test, y_pred_v2, zero_division=0)

print("Version 2 Metrics")
print("Accuracy:", accuracy_v2)
print("Precision:", precision_v2)
print("Recall:", recall_v2)
print("F1 Score:", f1_v2)

Version 2 Metrics
Accuracy: 0.9
Precision: 1.0
Recall: 0.6875
F1 Score: 0.8148148148148148

In [82]:
with mlflow.start_run(run_name="Random_Forest_Version_2"):

    mlflow.log_param("model", "Random Forest")
    mlflow.log_param("version", 2)
    mlflow.log_param("n_estimators", 200)
    mlflow.log_param("max_depth", 8)

    mlflow.log_metric("accuracy", accuracy_v2)
    mlflow.log_metric("precision", precision_v2)
    mlflow.log_metric("recall", recall_v2)
    mlflow.log_metric("f1_score", f1_v2)

    mlflow.sklearn.log_model(model_v2, "model")

    run_id_v2 = mlflow.active_run().info.run_id

    print("Version 2 run logged!")
    print("Run ID:", run_id_v2)

2026/09/18 08:28:46 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Version 2 run logged!
Run ID: 910d264a0709466ea1920c725b3169fe

In [83]:
model_uri_v2 = f"runs:/{run_id_v2}/model"

registered_v2 = mlflow.register_model(
    model_uri=model_uri_v2,
    name="Employee_Attrition_Model"
)

print("Version 2 registered successfully!")
print("Model name:", registered_v2.name)
print("Version:", registered_v2.version)

Registered model 'Employee_Attrition_Model' already exists. Creating a new version of this model...
2026/09/18 08:29:06 WARNING mlflow.tracking._model_registry.fluent: Run with id 910d264a0709466ea1920c725b3169fe has no artifacts at artifact path 'model', registering model based on models:/m-99694bbe17544cab88f141bba32bee69 instead

Version 2 registered successfully!
Model name: Employee_Attrition_Model
Version: 2

Created version '2' of model 'Employee_Attrition_Model'.

In [84]:
model_v3 = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=5,
    random_state=42
)

# Train Version 3
model_v3.fit(X_train, y_train)

# Predict
y_pred_v3 = model_v3.predict(X_test)

# Metrics
accuracy_v3 = accuracy_score(y_test, y_pred_v3)
precision_v3 = precision_score(y_test, y_pred_v3, zero_division=0)
recall_v3 = recall_score(y_test, y_pred_v3, zero_division=0)
f1_v3 = f1_score(y_test, y_pred_v3, zero_division=0)

print("Version 3 Metrics")
print("Accuracy:", accuracy_v3)
print("Precision:", precision_v3)
print("Recall:", recall_v3)
print("F1 Score:", f1_v3)

Version 3 Metrics
Accuracy: 0.89
Precision: 1.0
Recall: 0.65625
F1 Score: 0.7924528301886793

In [85]:
with mlflow.start_run(run_name="Random_Forest_Version_3"):

    mlflow.log_param("model", "Random Forest")
    mlflow.log_param("version", 3)
    mlflow.log_param("n_estimators", 300)
    mlflow.log_param("max_depth", 10)
    mlflow.log_param("min_samples_split", 5)

    mlflow.log_metric("accuracy", accuracy_v3)
    mlflow.log_metric("precision", precision_v3)
    mlflow.log_metric("recall", recall_v3)
    mlflow.log_metric("f1_score", f1_v3)

    mlflow.sklearn.log_model(model_v3, "model")

    run_id_v3 = mlflow.active_run().info.run_id

print("Version 3 run logged!")
print("Run ID:", run_id_v3)

2026/09/18 08:29:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Version 3 run logged!
Run ID: 10273fa01d284b3982b4cb0143f5ec82

In [88]:
from mlflow.tracking import MlflowClient

client = MlflowClient()

versions = client.search_model_versions(
    "name='Employee_Attrition_Model'"
)

for v in versions:
    print(
        "Model:",
        v.name,
        "| Version:",
        v.version,
        "| Run ID:",
        v.run_id
    )

Model: Employee_Attrition_Model | Version: 2 | Run ID: 910d264a0709466ea1920c725b3169fe
Model: Employee_Attrition_Model | Version: 1 | Run ID: 77b8bad91586477689c5e7b25219d3a4

In [89]:
print(run_id_v3)

10273fa01d284b3982b4cb0143f5ec82

In [90]:
model_uri_v3 = f"runs:/{run_id_v3}/model"

registered_v3 = mlflow.register_model(
    model_uri=model_uri_v3,
    name="Employee_Attrition_Model"
)

print("Version 3 registered successfully!")
print("Model name:", registered_v3.name)
print("Version:", registered_v3.version)

Registered model 'Employee_Attrition_Model' already exists. Creating a new version of this model...
2026/09/18 08:30:51 WARNING mlflow.tracking._model_registry.fluent: Run with id 10273fa01d284b3982b4cb0143f5ec82 has no artifacts at artifact path 'model', registering model based on models:/m-ba10d8a2af4d4cfabd6540d3662b2396 instead

Version 3 registered successfully!
Model name: Employee_Attrition_Model
Version: 3

Created version '3' of model 'Employee_Attrition_Model'.

In [91]:
from mlflow.tracking import MlflowClient

client = MlflowClient()

versions = client.search_model_versions(
    "name='Employee_Attrition_Model'"
)

for v in sorted(versions, key=lambda x: int(x.version)):
    print(
        "Model:",
        v.name,
        "| Version:",
        v.version,
        "| Run ID:",
        v.run_id
    )

Model: Employee_Attrition_Model | Version: 1 | Run ID: 77b8bad91586477689c5e7b25219d3a4
Model: Employee_Attrition_Model | Version: 2 | Run ID: 910d264a0709466ea1920c725b3169fe
Model: Employee_Attrition_Model | Version: 3 | Run ID: 10273fa01d284b3982b4cb0143f5ec82

In [5]:
%%writefile ml_pipeline.py
from pathlib import Path
import json
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
BASE_DIR = Path(__file__).resolve().parent
DATA_PATH = BASE_DIR / "mlops_employee_attrition_dataset.csv"
ARTIFACT_DIR = BASE_DIR / "artifacts"
OUTPUT_DIR = BASE_DIR / "outputs"
MODEL_PATH = ARTIFACT_DIR / "employee_attrition_pipeline.joblib"
REPORT_PATH = OUTPUT_DIR / "pipeline_report.txt"
METRICS_PATH = OUTPUT_DIR / "metrics.json"
PREDICTION_PATH = OUTPUT_DIR / "sample_prediction.csv"
def load_data():
    print("\nSTEP 1: Loading dataset...")
    df = pd.read_csv(DATA_PATH)
    df = df.drop_duplicates()
    print("Dataset loaded successfully")
    print("Dataset shape:", df.shape)
    return df
def prepare_data(df):
    print("\nSTEP 2: Preparing data...")
    y = df["attrition"]
    X = df.drop("attrition", axis=1)
    X = X.drop(["employee_id"], axis=1)
    num_cols = X.select_dtypes(include=["int64", "float64"]).columns
    cat_cols = X.select_dtypes(include=["object"]).columns
    print("Number of input features:", X.shape[1])
    print("Numerical columns:", list(num_cols))
    print("Categorical columns:", list(cat_cols))
    print("\nTarget distribution:")
    print(y.value_counts().sort_index())
    return X, y, num_cols, cat_cols
def split_data(X, y):
    print("\nSTEP 3: Splitting dataset...")
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    print("Training records:", X_train.shape[0])
    print("Testing records :", X_test.shape[0])
    return X_train, X_test, y_train, y_test
def build_pipeline(num_cols, cat_cols):
    print("\nSTEP 4: Building ML pipeline...")
    numeric_transformer = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])
    categorical_transformer = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ])
    preprocessor = ColumnTransformer([
        ("num", numeric_transformer, num_cols),
        ("cat", categorical_transformer, cat_cols)
    ])
    classifier = LogisticRegression(
        C=0.5, max_iter=2000, random_state=42
    )
    pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("classifier", classifier)
    ])
    print("Pipeline created successfully")
    return pipeline
def train_model(pipeline, X_train, y_train):
    print("\nSTEP 5: Training model...")
    pipeline.fit(X_train, y_train)
    print("Model training completed")
    return pipeline
def evaluate_model(pipeline, X_test, y_test):
    print("\nSTEP 6: Evaluating model...")
    y_pred = pipeline.predict(X_test)
    metrics = {
        "accuracy": float(accuracy_score(y_test, y_pred)),
        "precision": float(precision_score(y_test, y_pred, zero_division=0)),
        "recall": float(recall_score(y_test, y_pred, zero_division=0)),
        "f1_score": float(f1_score(y_test, y_pred, zero_division=0))
    }
    print("\nMODEL PERFORMANCE")
    print("-------------------------")
    print(f"Accuracy  : {metrics['accuracy']:.4f}")
    print(f"Precision : {metrics['precision']:.4f}")
    print(f"Recall    : {metrics['recall']:.4f}")
    print(f"F1 Score  : {metrics['f1_score']:.4f}")
    return metrics
def save_model(pipeline):
    print("\nSTEP 7: Saving trained pipeline...")
    ARTIFACT_DIR.mkdir(exist_ok=True)
    joblib.dump(pipeline, MODEL_PATH)
    print("Pipeline saved:", MODEL_PATH)
def test_saved_model(X_test):
    print("\nSTEP 8: Loading saved pipeline...")
    loaded_pipeline = joblib.load(MODEL_PATH)
    sample = X_test.iloc[[0]].copy()
    prediction = loaded_pipeline.predict(sample)[0]
    if hasattr(prediction, "item"):
        prediction = prediction.item()
    print("\nSample employee:")
    print(sample)
    print("\nPrediction:", prediction)
    result = sample.copy()
    result["Prediction"] = prediction
    OUTPUT_DIR.mkdir(exist_ok=True)
    result.to_csv(PREDICTION_PATH, index=False)
    print("Prediction saved:", PREDICTION_PATH)
    return prediction
def save_report(metrics, prediction):
    print("\nSTEP 9: Saving execution results...")
    OUTPUT_DIR.mkdir(exist_ok=True)
    with open(METRICS_PATH, "w") as f:
        json.dump(metrics, f, indent=4)
    with open(REPORT_PATH, "w") as f:
        f.write("MODULE 2 - PRACTICE 2\n")
        f.write("END-TO-END ML PIPELINE IMPLEMENTATION\n")
        f.write("=======================================\n\n")
        f.write("Dataset: mlops_employee_attrition_dataset(1).csv\n")
        f.write("Target: attrition\n")
        f.write("Model: Logistic Regression\n")
        f.write("Pipeline: Preprocessing + Training + Prediction\n\n")
        f.write(f"Accuracy  : {metrics['accuracy']:.4f}\n")
        f.write(f"Precision : {metrics['precision']:.4f}\n")
        f.write(f"Recall    : {metrics['recall']:.4f}\n")
        f.write(f"F1 Score  : {metrics['f1_score']:.4f}\n")
        f.write(f"\nSample Prediction: {prediction}\n")
        f.write("\nPipeline executed successfully.\n")
    print("Metrics saved:", METRICS_PATH)
    print("Report saved :", REPORT_PATH)
def main():
    print("\n==========================================")
    print(" EMPLOYEE ATTRITION END-TO-END ML PIPELINE")
    print("==========================================")
    df = load_data()
    X, y, num_cols, cat_cols = prepare_data(df)
    X_train, X_test, y_train, y_test = split_data(X, y)
    pipeline = build_pipeline(num_cols, cat_cols)
    pipeline = train_model(pipeline, X_train, y_train)
    metrics = evaluate_model(pipeline, X_test, y_test)
    save_model(pipeline)
    prediction = test_saved_model(X_test)
    save_report(metrics, prediction)
    print("\nPIPELINE COMPLETED SUCCESSFULLY")
if __name__ == "__main__":
    main()

Overwriting ml_pipeline.py

In [6]:
import os
print('ml_pipeline.py exists:', os.path.exists('ml_pipeline.py'))
print('Current folder:', os.getcwd())

ml_pipeline.py exists: True
Current folder: C:\Users\ajith\Desktop\Employee_Attrition_MLOps

In [7]:
%run ml_pipeline.py

==========================================
 EMPLOYEE ATTRITION END-TO-END ML PIPELINE
==========================================

STEP 1: Loading dataset...
Dataset loaded successfully
Dataset shape: (500, 10)

STEP 2: Preparing data...
Number of input features: 8
Numerical columns: ['age', 'experience_years', 'salary', 'job_satisfaction', 'work_life_balance', 'training_hours']
Categorical columns: ['department', 'education']

Target distribution:
attrition
0    342
1    158
Name: count, dtype: int64

STEP 3: Splitting dataset...
Training records: 400
Testing records : 100

STEP 4: Building ML pipeline...
Pipeline created successfully

STEP 5: Training model...
Model training completed

STEP 6: Evaluating model...

MODEL PERFORMANCE
-------------------------
Accuracy  : 0.8000
Precision : 0.7308
Recall    : 0.5938
F1 Score  : 0.6552

STEP 7: Saving trained pipeline...
Pipeline saved: C:\Users\ajith\Desktop\Employee_Attrition_MLOps\artifacts\employee_attrition_pipeline.joblib

STEP 8: Loading saved pipeline...

Sample employee:
     age  experience_years  salary  department education  job_satisfaction  \
451   45                21   42674  Operations   Masters                 4

     work_life_balance  training_hours
451                  3              55

Prediction: 0
Prediction saved: C:\Users\ajith\Desktop\Employee_Attrition_MLOps\outputs\sample_prediction.csv

STEP 9: Saving execution results...
Metrics saved: C:\Users\ajith\Desktop\Employee_Attrition_MLOps\outputs\metrics.json
Report saved : C:\Users\ajith\Desktop\Employee_Attrition_MLOps\outputs\pipeline_report.txt

PIPELINE COMPLETED SUCCESSFULLY

In [8]:
import json
import pandas as pd

print("METRICS")
print("=======")

with open("outputs/metrics.json") as f:
    metrics = json.load(f)

for key, value in metrics.items():
    print(f"{key}: {value:.4f}")

print("\nSAMPLE PREDICTION")
print("=================")

prediction = pd.read_csv("outputs/sample_prediction.csv")
display(prediction)

print("\nFILES GENERATED")
print("================")
print("artifacts/employee_attrition_pipeline.joblib")
print("outputs/metrics.json")
print("outputs/pipeline_report.txt")
print("outputs/sample_prediction.csv")

METRICS
=======
accuracy: 0.8000
precision: 0.7308
recall: 0.5938
f1_score: 0.6552

SAMPLE PREDICTION
=================

,age,experience_years,salary,department,education,job_satisfaction,work_life_balance,training_hours,Prediction
0,45,21,42674,Operations,Masters,4,3,55,0

FILES GENERATED
================
artifacts/employee_attrition_pipeline.joblib
outputs/metrics.json
outputs/pipeline_report.txt
outputs/sample_prediction.csv

In [1]:
pip install perfect

Collecting perfect
  Using cached perfect-0.0.1-py3-none-any.whl.metadata (2.0 kB)
Using cached perfect-0.0.1-py3-none-any.whl (4.3 kB)
Installing collected packages: perfect
Successfully installed perfect-0.0.1
Note: you may need to restart the kernel to use updated packages.